export interface Tour {
  id: string
  slug: string
  title: string
  location: string
  country: string
  category: 'calcio' | 'ciclismo' | 'atletica' | 'tennis' | 'motorsport' | 'rugby' | 'basket' | 'pallavolo'
  categoryLabel: string
  startDate: string
  endDate: string
  duration: string
  image: string
  shortDescription: string
  longDescription: string
  included: string[]
  highlights: string[]
  maxParticipants: number
  difficulty: 'facile' | 'media' | 'impegnativa'
  featured: boolean
}

export const tours: Tour[] = [
  {
    id: '1',
    slug: 'grande-classico-calcio-roma',
    title: 'Il Grande Classico del Sud',
    location: 'Roma & Napoli',
    country: 'Italia',
    category: 'calcio',
    categoryLabel: 'Calcio',
    startDate: '2026-05-15',
    endDate: '2026-05-19',
    duration: '5 giorni',
    image: '/images/tour-football-italy.jpg',
    shortDescription: 'Un emozionante viaggio nel cuore del calcio italiano tra Roma e Napoli, con partite da brivido e visite culturali indimenticabili.',
    longDescription: `Immergetevi nell'atmosfera unica del calcio italiano in uno dei tour più entusiasmanti che abbiamo mai organizzato. Partirete da Roma, città eterna e culla del football italiano, dove assisterete a una partita di campionato mozzafiato in uno dei più antichi impianti sportivi della penisola.\n\nNel secondo giorno raggiungerete Napoli, la città del sole e della passione calcistica senza pari. Le strade del quartiere spagnolo vibrano ancora delle gesta dei grandi campioni del passato e il tifo partenopeo è qualcosa che si vive solo in questa città.\n\nIl tour include visita guidata alla città eterna, degustazione di prodotti tipici campani, sistemazione in hotel a 4 stelle nel centro storico e un accogliente guida locale che vi farà sentire come veri tifosi italiani.`,
    included: [
      '2 partite di calcio di Serie A',
      '4 notti in hotel 4 stelle',
      'Trasporti locali inclusi',
      'Guida sportiva bilingue',
      'Colazioni incluse',
      'Visita guidata ai quartieri storici',
    ],
    highlights: [
      'Partita di Serie A a Roma',
      'Derby campano a Napoli',
      'Tour del centro storico di Roma',
      'Cena tradizionale napoletana',
      'Meet & Greet con ex calciatori',
    ],
    maxParticipants: 20,
    difficulty: 'facile',
    featured: true,
  },
  {
    id: '2',
    slug: 'tour-ciclismo-toscana',
    title: 'La Leggenda delle Strade Toscane',
    location: 'Toscana',
    country: 'Italia',
    category: 'ciclismo',
    categoryLabel: 'Ciclismo',
    startDate: '2026-04-18',
    endDate: '2026-04-22',
    duration: '5 giorni',
    image: '/images/tour-cycling-tuscany.jpg',
    shortDescription: 'Seguite i leggendari ciclisti sulle strade bianche della Toscana durante uno dei grandi appuntamenti del ciclismo europeo primaverile.',
    longDescription: `La Toscana in primavera è una delle esperienze più belle che uno sportivo possa vivere. Le strade bianche che attraversano le colline senesi diventano teatro di battaglie ciclistiche epiche, dove i campioni si sfidano in un paesaggio da cartolina.\n\nQuesto tour vi porterà lungo il percorso delle grandi classiche primaverili, con la possibilità di assistere alle tappe più spettacolari direttamente a bordo strada. I nostri esperti conoscono i punti migliori da cui seguire la corsa, lontano dalla folla ma con una visione privilegiata.\n\nOltre alle emozioni sportive, avrete modo di visitare le meraviglie di Siena e dei piccoli borghi medievali che punteggiano il paesaggio toscano, gustando i vini e i formaggi tipici della regione.`,
    included: [
      'Accesso VIP al percorso di gara',
      '4 notti in agriturismo tipico',
      'Transfer privato lungo il percorso',
      'Guida ciclistica esperta',
      'Pranzi e cene inclusi',
      'Degustazione vini toscani',
    ],
    highlights: [
      'Classica primaverile su strade bianche',
      'Visita a Siena medievale',
      'Degustazione Brunello di Montalcino',
      'Punti VIP lungo il percorso',
      'Incontro con ciclisti locali',
    ],
    maxParticipants: 16,
    difficulty: 'media',
    featured: true,
  },
  {
    id: '3',
    slug: 'atletica-roma-estate',
    title: 'Notti di Atletica sotto le Stelle',
    location: 'Roma',
    country: 'Italia',
    category: 'atletica',
    categoryLabel: 'Atletica',
    startDate: '2026-07-10',
    endDate: '2026-07-14',
    duration: '5 giorni',
    image: '/images/tour-athletics-rome.jpg',
    shortDescription: 'Assistete a un grande meeting internazionale di atletica leggera nella magica cornice notturna di Roma, tra storia millenaria e agonismo moderno.',
    longDescription: `Roma di notte è qualcosa di magico. Quando il sole tramonta sull'Olimpo degli dei e le luci artificiali illuminano le piste di tartan rosso, si crea un'atmosfera irripetibile che solo i grandi eventi di atletica sanno regalare.\n\nIl nostro tour vi porterà al cuore di un meeting internazionale di atletica leggera, uno dei più attesi del circuito europeo. Correrete metaforicamente con i campioni del mondo del salto con l'asta, della velocità e del mezzofondo, vivendo l'adrenalina dello sport puro.\n\nTra un evento e l'altro, avrete tempo per esplorare la Roma imperiale, visitare il Foro Romano all'alba e assaporare la cucina romanesca nei ristoranti del Trastevere.`,
    included: [
      '2 serate al meeting di atletica (posti tribuna A)',
      '4 notti in hotel 4 stelle centro',
      'Trasporti locali inclusi',
      'Guida culturale e sportiva',
      'Colazioni incluse',
      'Cena di gala con ex atleti',
    ],
    highlights: [
      'Meeting internazionale di atletica',
      'Tour del Foro Romano',
      'Cena nel Trastevere',
      'Sessione fotografica con atleti',
      'Visita al Colosseo',
    ],
    maxParticipants: 24,
    difficulty: 'facile',
    featured: true,
  },
  {
    id: '4',
    slug: 'tennis-roland-garros-parigi',
    title: 'Il Rosso della Terra di Parigi',
    location: 'Parigi',
    country: 'Francia',
    category: 'tennis',
    categoryLabel: 'Tennis',
    startDate: '2026-05-28',
    endDate: '2026-06-02',
    duration: '6 giorni',
    image: '/images/tour-tennis-french.jpg',
    shortDescription: 'Vivete la magia del più grande torneo tennistico su terra battuta a Parigi, con posti garantiti sui campi principali e l\'eleganza della capitale francese.',
    longDescription: `Parigi in giugno profuma di terra battuta, di champagne e di tennis d'élite. Il torneo internazionale su terra della capitale francese è uno dei quattro eventi più importanti del tennis mondiale, e assistere dal vivo alle semifinali e alla finale è un'esperienza che ogni appassionato di tennis deve vivere almeno una volta.\n\nIl nostro tour include biglietti garantiti per i giorni più emozionanti del torneo, con accesso ai campi laterali dove si svolgono partite di altissimo livello fin dalle prime ore del mattino. Avrete inoltre la possibilità di esplorare il villaggio del torneo e di godere delle aree riservate agli ospiti.\n\nNel tempo libero, Parigi vi aspetta con i suoi musei, i suoi caffè e la sua straordinaria gastronomia. Una vacanza sportiva che è anche un viaggio nella grande cultura europea.`,
    included: [
      'Biglietti per 4 giorni di torneo (Court Philippe-Chatrier)',
      '5 notti in hotel boutique 4 stelle',
      'Transfer aeroporto incluso',
      'Colazioni incluse',
      'Guida bilingue italiano-francese',
      'Welcome dinner nel Marais',
    ],
    highlights: [
      'Semifinali e quarti di finale',
      'Accesso al villaggio VIP',
      'Giro in barca sulla Senna',
      'Visita al Louvre',
      'Cena gastronomica stellata',
    ],
    maxParticipants: 14,
    difficulty: 'facile',
    featured: true,
  },
  {
    id: '5',
    slug: 'motorsport-circuiti-europei',
    title: 'Rombo di Motori tra le Alpi',
    location: 'Monaco & Austria',
    country: 'Europa',
    category: 'motorsport',
    categoryLabel: 'Motorsport',
    startDate: '2026-05-20',
    endDate: '2026-05-27',
    duration: '8 giorni',
    image: '/images/tour-motorsport-europe.jpg',
    shortDescription: 'Un tour esclusivo tra i circuiti più leggendari d\'Europa: la gloria di Monaco e la natura selvaggia dell\'Austria per vivere il motorsport nella sua forma più pura.',
    longDescription: `Il profumo della benzina, il rumore assordante dei motori e la velocità che sfida ogni limite umano. Il motorsport è molto più di uno sport: è un rito collettivo che unisce milioni di appassionati in tutto il mondo. E noi vi portiamo al centro di questo rito.\n\nIl tour parte da Nizza, porta verso Monaco dove le auto da corsa sfrecciano tra i palazzi e il porto yacht nella gara su circuito urbano più famosa del mondo. L'atmosfera del giovedì di gara, con le prove libere che echeggiano per i vicoli del Principato, è semplicemente indescrivibile.\n\nDa Monaco ci si sposta verso l'Austria attraverso le Alpi, dove un altro circuito leggendario annidato tra le montagne vi aspetta con la sua natura selvaggia e incontaminata. Due esperienze completamente diverse ma ugualmente emozionanti.`,
    included: [
      'Biglietti grandstand per entrambe le gare',
      '7 notti in hotel selezionati (4-5 stelle)',
      'Transfer privato Monaco-Austria',
      'Colazioni e 3 cene incluse',
      'Tour dei box (paddock tour)',
      'Guida sportiva specializzata motorsport',
    ],
    highlights: [
      'Gran Premio di Monaco',
      'Gran Premio d\'Austria',
      'Paddock tour con accesso speciale',
      'Cena nel porto di Monaco',
      'Escursione nelle Alpi austriache',
    ],
    maxParticipants: 12,
    difficulty: 'media',
    featured: false,
  },
  {
    id: '6',
    slug: 'rugby-sei-nazioni-londra',
    title: 'La Mischia di Londra',
    location: 'Londra',
    country: 'Gran Bretagna',
    category: 'rugby',
    categoryLabel: 'Rugby',
    startDate: '2026-09-12',
    endDate: '2026-09-16',
    duration: '5 giorni',
    image: '/images/tour-rugby-london.jpg',
    shortDescription: 'Vivete l\'intensità del rugby internazionale a Londra, con una delle partite più attese dell\'anno in una delle città più affascinanti d\'Europa.',
    longDescription: `Il rugby a Londra ha una tradizione centenaria che si respira in ogni pub, in ogni parco dove i ragazzi si lanciano l'ovale, nell'aria stessa della città. Portarvi qui per una partita internazionale significa immergersi in una cultura sportiva profondamente radicata e genuina.\n\nAssisterete a una partita internazionale di altissimo livello nel leggendario impianto di Twickenham, il tempio del rugby inglese. La cerimonia pre-partita, il canto degli inni nazionali e il tifo composto ma appassionato del pubblico britannico sono qualcosa che non si dimentica.\n\nNel corso del soggiorno londinese, avrete modo di esplorare la City, visitare i musei gratuiti di livello mondiale, godervi un traditional pub lunch e camminare lungo le rive del Tamigi. Londra è sempre una buona idea.`,
    included: [
      'Biglietti per partita internazionale di rugby',
      '4 notti in hotel 4 stelle a Londra',
      'Transfer aeroporto Heathrow incluso',
      'Oyster card per trasporti pubblici',
      'Guida italiana a Londra',
      'Colazioni incluse',
    ],
    highlights: [
      'Partita internazionale a Twickenham',
      'Tour dei musei storici londinesi',
      'Pranzo in pub storico di Londra',
      'Passeggiata a South Bank',
      'Shopping in Carnaby Street',
    ],
    maxParticipants: 20,
    difficulty: 'facile',
    featured: false,
  },
  {
    id: '7',
    slug: 'basket-madrid-eurolega',
    title: 'La Canestrata di Madrid',
    location: 'Madrid',
    country: 'Spagna',
    category: 'basket',
    categoryLabel: 'Basket',
    startDate: '2026-10-16',
    endDate: '2026-10-20',
    duration: '5 giorni',
    image: '/images/tour-basketball-madrid.jpg',
    shortDescription: 'Madrid è la capitale del basket europeo e voi sarete in prima fila per vivere l\'atmosfera incomparabile dell\'Eurolega in un palazzetto bollente.',
    longDescription: `Madrid è sinonimo di grandi passioni sportive, e il basket non fa eccezione. La tifoseria madrilena è tra le più calde d'Europa, capace di trasformare ogni palazzetto in un vulcano di emozioni quando la palla da basket rimbalza sul parquet.\n\nIl nostro tour vi porta nel cuore dell'Eurolega di basket, con due partite di altissimo livello da vedere dal vivo. Il palazzetto di 18.000 posti sold out, la musica a tutto volume, le cheerleader, gli schermi giganti: è uno spettacolo nello spettacolo.\n\nMadrid è anche una città splendida da esplorare: il Prado, il Retiro, il Mercado de San Miguel con le sue tapas, i quartieri storici di La Latina e Malasaña. Un tour sportivo e culturale che soddisferà ogni tipo di viaggiatore.`,
    included: [
      '2 partite di Eurolega di basket',
      '4 notti in hotel 4 stelle Madrid centro',
      'Transfer aeroporto incluso',
      'Metro card per 4 giorni',
      'Guida italoespagnola',
      'Colazioni e 1 cena di tapas',
    ],
    highlights: [
      '2 partite di Eurolega',
      'Visita al Museo del Prado',
      'Tapas tour nel quartiere La Latina',
      'Giro nel Parco del Retiro',
      'Serata flamenco',
    ],
    maxParticipants: 22,
    difficulty: 'facile',
    featured: false,
  },
  {
    id: '8',
    slug: 'beach-volley-costa-italiana',
    title: 'Arena di Sabbia sul Mediterraneo',
    location: 'Lido di Venezia & Rimini',
    country: 'Italia',
    category: 'pallavolo',
    categoryLabel: 'Beach Volley',
    startDate: '2026-08-05',
    endDate: '2026-08-10',
    duration: '6 giorni',
    image: '/images/tour-volleyball-beach.jpg',
    shortDescription: 'Sole, spiaggia e beach volley di alto livello: un tour estivo tra Lido di Venezia e Rimini per vivere i campionati italiani ed europei sulla sabbia.',
    longDescription: `L'estate italiana ha un ritmo tutto suo, scandito dal calore del sole, dall'azzurro del mare Adriatico e dalla sabbia calda delle spiagge della Riviera. E quando su quella sabbia si gioca a beach volley di livello internazionale, l'atmosfera diventa qualcosa di veramente speciale.\n\nIl tour inizia a Lido di Venezia, dove la laguna incontra il mare aperto e dove si svolge uno dei tornei di beach volley più belli d'Italia per l'ambientazione. Da qui ci si sposta verso Rimini, cuore della Riviera Romagnola, dove il campionato europeo porta le migliori coppie del continente a sfidarsi sul cemento bianco della sabbia.\n\nTra le partite, avrete tempo per nuotare nel mare Adriatico, esplorare Venezia con le sue calli e i suoi canali, gustare i frutti di mare freschissimi nelle trattorie di riva e vivere la dolce vita italiana nella sua versione più autentica e estiva.`,
    included: [
      'Biglietti per 3 giorni di torneo',
      '5 notti (2 Venezia + 3 Rimini)',
      'Transfer Venezia-Rimini incluso',
      'Colazioni e 2 cene di pesce',
      'Guida sportiva italiana',
      'Escursione in gondola a Venezia',
    ],
    highlights: [
      'Torneo beach volley a Lido di Venezia',
      'Campionato europeo a Rimini',
      'Giro in gondola a Venezia',
      'Degustazione frutti di mare',
      'Tramonto sul Canal Grande',
    ],
    maxParticipants: 18,
    difficulty: 'facile',
    featured: false,
  },
]

export const categories = [
  { value: 'tutti', label: 'Tutti i Tour' },
  { value: 'calcio', label: 'Calcio' },
  { value: 'ciclismo', label: 'Ciclismo' },
  { value: 'atletica', label: 'Atletica' },
  { value: 'tennis', label: 'Tennis' },
  { value: 'motorsport', label: 'Motorsport' },
  { value: 'rugby', label: 'Rugby' },
  { value: 'basket', label: 'Basket' },
  { value: 'pallavolo', label: 'Beach Volley' },
]

export const countries = [
  { value: 'tutti', label: 'Tutti i Paesi' },
  { value: 'Italia', label: 'Italia' },
  { value: 'Francia', label: 'Francia' },
  { value: 'Spagna', label: 'Spagna' },
  { value: 'Gran Bretagna', label: 'Gran Bretagna' },
  { value: 'Europa', label: 'Europa' },
]
